
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Calendar calendar2;

	private global::Gtk.VButtonBox vbuttonbox1;

	private global::Gtk.Button buttonUnesi;

	private global::Gtk.Button buttonIzmjeni;

	private global::Gtk.Button buttonIzbrisi;

	private global::Gtk.Button buttonBitniDogadaji;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.NodeView nodeview1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(15));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.calendar2 = new global::Gtk.Calendar();
		this.calendar2.CanFocus = true;
		this.calendar2.Name = "calendar2";
		this.calendar2.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.vbox2.Add(this.calendar2);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.calendar2]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbuttonbox1 = new global::Gtk.VButtonBox();
		this.vbuttonbox1.Name = "vbuttonbox1";
		this.vbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.buttonUnesi = new global::Gtk.Button();
		this.buttonUnesi.CanFocus = true;
		this.buttonUnesi.Name = "buttonUnesi";
		this.buttonUnesi.UseUnderline = true;
		this.buttonUnesi.Label = global::Mono.Unix.Catalog.GetString("Unesi Događaj");
		this.vbuttonbox1.Add(this.buttonUnesi);
		global::Gtk.ButtonBox.ButtonBoxChild w2 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.buttonUnesi]));
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.buttonIzmjeni = new global::Gtk.Button();
		this.buttonIzmjeni.CanFocus = true;
		this.buttonIzmjeni.Name = "buttonIzmjeni";
		this.buttonIzmjeni.UseUnderline = true;
		this.buttonIzmjeni.Label = global::Mono.Unix.Catalog.GetString("Izmjeni Događaj");
		this.vbuttonbox1.Add(this.buttonIzmjeni);
		global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.buttonIzmjeni]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.buttonIzbrisi = new global::Gtk.Button();
		this.buttonIzbrisi.CanFocus = true;
		this.buttonIzbrisi.Name = "buttonIzbrisi";
		this.buttonIzbrisi.UseUnderline = true;
		this.buttonIzbrisi.Label = global::Mono.Unix.Catalog.GetString("Izbriši događaj");
		this.vbuttonbox1.Add(this.buttonIzbrisi);
		global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.buttonIzbrisi]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.buttonBitniDogadaji = new global::Gtk.Button();
		this.buttonBitniDogadaji.CanFocus = true;
		this.buttonBitniDogadaji.Name = "buttonBitniDogadaji";
		this.buttonBitniDogadaji.UseUnderline = true;
		this.buttonBitniDogadaji.Label = global::Mono.Unix.Catalog.GetString("Bitni događaji");
		this.vbuttonbox1.Add(this.buttonBitniDogadaji);
		global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.buttonBitniDogadaji]));
		w5.Position = 3;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox2.Add(this.vbuttonbox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbuttonbox1]));
		w6.Position = 1;
		this.hbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.nodeview1 = new global::Gtk.NodeView();
		this.nodeview1.CanFocus = true;
		this.nodeview1.Name = "nodeview1";
		this.GtkScrolledWindow.Add(this.nodeview1);
		this.hbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow]));
		w9.Position = 1;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w10.Position = 0;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 652;
		this.DefaultHeight = 464;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
